### ISSUE TITLE
Remove IP addresses from Segment tracking calls and scrub existing IP's in our data warehouse

### ISSUE THREAD

**Issue by localredhead** [uport-project/iis#31]
IP address information needs to be zero'd out in both the tracking calls for all client code as well as scrubbed from our data warehouse

Here is how to do it from the analytics clients:  https://segment.com/docs/sources/website/analytics.js/#anonymizing-ip

pass a new object in the payload, `{context: { ip: 0.0.0.0 }}`.

- [x] in the mobile app this should be easy to do in the `metrics.js` file.  
- [x] in the docs-site we will likely need to clone this plugin, and modify the default `.page()` call to zero-out the IP's.  https://github.com/benjaminhoffman/gatsby-plugin-segment-js/blob/master/src/gatsby-ssr.js

**Comment by gbugyis** [comment]
Cristobal helped out getting the IPs cleaned out of the warehouse. Last step is to modify the docs site tracking calls.

**Comment by gbugyis** [comment]
Also updated the analytics.page() call on uport.me to zero out IPs.
